export const SPELL_DATA = {
  AHB: {
    base1: 100,
    baseDmg: 6500,
    castTime: 0,
    focusable: false,
    id: 'AHB',
    level: 255,
    lockoutTime: 0,
    manaCost: 0,
    max: 0,
    name: 'Hedgewizard\'s Spell',
    origCastTime: 0,
    recastTime: 0,
    resist: 'DISEASE',
    skill: 24,
    target: 'SINGLE',
    timer: 'AB',
    type3Dmg: 0
  },
  AM: {
    baseDmg: 1206,
    castTime: 0,
    focusable: true,
    id: 'AM',
    level: 255,
    lockoutTime: 0,
    manaCost: 0,
    name: 'Arcane Melody Effect III',
    origCastTime: 0,
    recastTime: 0,
    resist: 'MAGIC',
    skill: 98,
    target: 'SINGLE',
    timer: 'AM',
    type3Dmg: 0
  },
  ASVI: {
    base1: 100,
    baseDmg: 225,
    castTime: 0,
    focusable: true,
    id: 'ASVI',
    level: 255,
    lockoutTime: 0,
    manaCost: 0,
    name: 'Arcane Strike VI',
    origCastTime: 0,
    recastTime: 0,
    resist: 'MAGIC',
    skill: 52,
    spellDmgCap: 225,
    target: 'SINGLE',
    timer: 'ASVI',
    type3Dmg: 0
  },
  BFVI: {
    base1: 100,
    baseDmg: 10000,
    castTime: 0,
    focusable: true,
    id: 'BFVI',
    level: 255,
    lockoutTime: 0,
    manaCost: 0,
    name: 'Blaze of Fire VI',
    origCastTime: 0,
    recastTime: 0,
    resist: 'FIRE',
    skill: 52,
    target: 'SINGLE',
    timer: 'BFVI',
    type3Dmg: 0
  },
  BOVI: {
    base1: 100,
    baseDmg: 510,
    castTime: 0,
    focusable: true,
    id: 'BOVI',
    level: 255,
    lockoutTime: 0,
    manaCost: 0,
    name: 'Burst of Ice VI',
    origCastTime: 0,
    recastTime: 0,
    resist: 'COLD',
    skill: 52,
    target: 'SINGLE',
    timer: 'BOVI',
    type3Dmg: 0
  },
  BOIX: {
    base1: 100,
    baseDmg: 1050,
    castTime: 0,
    focusable: true,
    id: 'BOIX',
    level: 255,
    lockoutTime: 0,
    manaCost: 0,
    name: 'Burst of Ice X',
    origCastTime: 0,
    recastTime: 0,
    resist: 'COLD',
    skill: 52,
    target: 'SINGLE',
    timer: 'BOIX',
    type3Dmg: 0
  },
  DR: {
    base1: 160,
    baseDmg: 21944,
    castTime: 0,
    focusable: true,
    id: 'DR',
    level: 255,
    lockoutTime: 0,
    manaCost: 0,
    name: 'Dichotomic Reinforced Strike 6',
    origCastTime: 0,
    recastTime: 6000,
    resist: 'CHROMATIC',
    skill: 24,
    target: 'SINGLE',
    timer: 'DR',
    type3Dmg: 0
  },
  FCVII: {
    base1: 100,
    baseDmg: 540,
    castTime: 0,
    focusable: true,
    id: 'FCVII',
    level: 255,
    lockoutTime: 0,
    manaCost: 0,
    name: 'Force of Corruption VII',
    origCastTime: 0,
    recastTime: 0,
    resist: 'CORRUPTION',
    skill: 52,
    target: 'SINGLE',
    timer: 'FCVII',
    type3Dmg: 0
  },
  FCX: {
    base1: 100,
    baseDmg: 945,
    castTime: 0,
    focusable: true,
    id: 'FCX',
    level: 255,
    lockoutTime: 0,
    manaCost: 0,
    name: 'Force of Corruption X',
    origCastTime: 0,
    recastTime: 0,
    resist: 'CORRUPTION',
    skill: 52,
    target: 'SINGLE',
    timer: 'FCX',
    type3Dmg: 0
  },
  FOMIX: {
    base1: 100,
    baseDmg: 900,
    castTime: 0,
    focusable: true,
    id: 'FOMIX',
    level: 255,
    lockoutTime: 0,
    manaCost: 0,
    name: 'Force of Magic IX',
    origCastTime: 0,
    recastTime: 0,
    resist: 'MAGIC',
    skill: 52,
    target: 'SINGLE',
    timer: 'FOMIX',
    type3Dmg: 0
  },
  FOMVII: {
    base1: 100,
    baseDmg: 600,
    castTime: 0,
    focusable: true,
    id: 'FOMVII',
    level: 255,
    lockoutTime: 0,
    manaCost: 0,
    name: 'Force of Magic VII',
    origCastTime: 0,
    recastTime: 0,
    resist: 'MAGIC',
    skill: 52,
    target: 'SINGLE',
    timer: 'FOMVII',
    type3Dmg: 0
  },
  FOMXIII: {
    base1: 100,
    baseDmg: 1500,
    castTime: 0,
    focusable: true,
    id: 'FOMXIII',
    level: 255,
    lockoutTime: 0,
    manaCost: 0,
    name: 'Force of Magic XIII',
    origCastTime: 0,
    recastTime: 0,
    resist: 'MAGIC',
    skill: 52,
    target: 'SINGLE',
    timer: 'FOMXIII',
    type3Dmg: 0
  },
  FOMXV: {
    base1: 100,
    baseDmg: 1800,
    castTime: 0,
    focusable: true,
    id: 'FOMXV',
    level: 255,
    lockoutTime: 0,
    manaCost: 0,
    name: 'Force of Magic XV',
    origCastTime: 0,
    recastTime: 0,
    resist: 'MAGIC',
    skill: 52,
    target: 'SINGLE',
    timer: 'FOMXV',
    type3Dmg: 0
  },
  FSVI: {
    base1: 100,
    baseDmg: 225,
    castTime: 0,
    focusable: true,
    id: 'FSVI',
    level: 255,
    lockoutTime: 0,
    manaCost: 0,
    name: 'Fiery Strike VI',
    origCastTime: 0,
    recastTime: 0,
    resist: 'FIRE',
    skill: 52,
    spellDmgCap: 225,
    target: 'SINGLE',
    timer: 'FSVI',
    type3Dmg: 0
  },
  FSVII: {
    base1: 100,
    baseDmg: 250,
    castTime: 0,
    focusable: true,
    id: 'FSVII',
    level: 255,
    lockoutTime: 0,
    manaCost: 0,
    name: 'Fiery Strike VII',
    origCastTime: 0,
    recastTime: 0,
    resist: 'FIRE',
    skill: 52,
    spellDmgCap: 250,
    target: 'SINGLE',
    timer: 'FSVII',
    type3Dmg: 0
  },
  FZVI: {
    base1: 100,
    baseDmg: 225,
    castTime: 0,
    focusable: true,
    id: 'FZVI',
    level: 255,
    lockoutTime: 0,
    manaCost: 0,
    name: 'Freezing Strike VI',
    origCastTime: 0,
    recastTime: 0,
    resist: 'COLD',
    skill: 52,
    spellDmgCap: 225,
    target: 'SINGLE',
    timer: 'FZVI',
    type3Dmg: 0
  },
  FW: {
    baseDmg: 3365,
    castTime: 0,
    focusable: true,
    id: 'FW',
    level: 255,
    lockoutTime: 0,
    manaCost: 0,
    name: 'Frostweave Strike III',
    origCastTime: 0,
    recastTime: 0,
    resist: 'COLD',
    skill: 24,
    target: 'SINGLE',
    timer: 'FW',
    type3Dmg: 0
  },
  HOM3: {
    base1: 100,
    baseDmg: 7000,
    castTime: 0,
    focusable: true,
    id: 'HOM3',
    level: 255,
    lockoutTime: 0,
    manaCost: 0,
    name: 'Hammer of Magic III',
    origCastTime: 0,
    recastTime: 0,
    resist: 'MAGIC',
    skill: 52,
    target: 'SINGLE',
    timer: 'HOM3',
    type3Dmg: 0
  },
  MR: {
    baseDmg: 4137,
    castTime: 0,
    focusable: true,
    id: 'MR',
    level: 255,
    lockoutTime: 0,
    manaCost: 0,
    max: 0,
    name: 'Mana Reciprocation Strike III',
    origCastTime: 0,
    recastTime: 0,
    resist: 'CHROMATIC',
    skill: 5,
    target: 'SINGLE',
    timer: 'MRR',
    type3Dmg: 0
  },
  MRR: {
    baseDmg: 4551,
    castTime: 0,
    focusable: true,
    id: 'MRR',
    level: 255,
    lockoutTime: 0,
    manaCost: 0,
    max: 0,
    name: 'Mana Re-Reciprocation Strike III',
    origCastTime: 0,
    recastTime: 0,
    resist: 'CHROMATIC',
    skill: 5,
    target: 'SINGLE',
    timer: 'MRR',
    type3Dmg: 0
  },
  MRRR: {
    baseDmg: 5006,
    castTime: 0,
    focusable: true,
    id: 'MRRR',
    level: 255,
    lockoutTime: 0,
    manaCost: 0,
    max: 0,
    name: 'Mana Re-Re-Reciprocation Strike III',
    origCastTime: 0,
    recastTime: 0,
    resist: 'CHROMATIC',
    skill: 5,
    target: 'SINGLE',
    timer: 'MRRR',
    type3Dmg: 0
  },
  MRRRR: {
    baseDmg: 5507,
    castTime: 0,
    focusable: true,
    id: 'MRRRR',
    level: 255,
    lockoutTime: 0,
    manaCost: 0,
    max: 0,
    name: 'Mana Re-Re-Re-Reciprocation Strike III',
    origCastTime: 0,
    recastTime: 0,
    resist: 'CHROMATIC',
    skill: 5,
    target: 'SINGLE',
    timer: 'MRRRR',
    type3Dmg: 0
  },
  OS: {
    base1: 100,
    baseDmg: 4000,
    castTime: 0,
    focusable: false,
    id: 'OS',
    level: 255,
    lockoutTime: 0,
    manaCost: 0,
    name: 'Obulus Strike',
    origCastTime: 0,
    recastTime: 0,
    resist: 'CHROMATIC',
    skill: 52,
    target: 'SINGLE',
    timer: 'OS',
    type3Dmg: 0
  },
  SODIX: {
    base1: 100,
    baseDmg: 900,
    castTime: 0,
    focusable: true,
    id: 'SODIX',
    level: 255,
    lockoutTime: 0,
    manaCost: 0,
    name: 'Strike of Disease IV',
    origCastTime: 0,
    recastTime: 0,
    resist: 'DISEASE',
    skill: 52,
    target: 'SINGLE',
    timer: 'SODIX',
    type3Dmg: 0
  },
  SOFV: {
    base1: 100,
    baseDmg: 420,
    castTime: 0,
    focusable: true,
    id: 'SOFV',
    level: 255,
    lockoutTime: 0,
    manaCost: 0,
    name: 'Strike of Flames V',
    origCastTime: 0,
    recastTime: 0,
    resist: 'FIRE',
    skill: 52,
    target: 'SINGLE',
    timer: 'SOFV',
    type3Dmg: 0
  },
  SOFXIII: {
    base1: 100,
    baseDmg: 1500,
    castTime: 0,
    focusable: true,
    id: 'SOFXIII',
    level: 255,
    lockoutTime: 0,
    manaCost: 0,
    name: 'Strike of Flames XIII',
    origCastTime: 0,
    recastTime: 0,
    resist: 'FIRE',
    skill: 52,
    target: 'SINGLE',
    timer: 'SOFXIII',
    type3Dmg: 0
  },
  SOFXIV: {
    base1: 100,
    baseDmg: 1650,
    castTime: 0,
    focusable: true,
    id: 'SOFXIV',
    level: 255,
    lockoutTime: 0,
    manaCost: 0,
    name: 'Strike of Flames XIV',
    origCastTime: 0,
    recastTime: 0,
    resist: 'FIRE',
    skill: 52,
    target: 'SINGLE',
    timer: 'SOFXIV',
    type3Dmg: 0
  },
  TC: {
    baseDmg: 0,
    beneficial: true,
    castTime: 0,
    focusable: false,
    id: 'TC',
    level: 85,
    lockoutTime: 1500,
    manaCost: 1,
    name: 'Twincast Rk. III',
    origCastTime: 0,
    recastTime: 300000,
    resist: 'NONE',
    skill: 4,
    target: 'SELF',
    timer: 'twincast',
    type3Dmg: 0
  },
  VOSIV: {
    base1: 100,
    baseDmg: 3200,
    castTime: 0,
    focusable: true,
    id: 'VOSIV',
    level: 255,
    lockoutTime: 0,
    manaCost: 0,
    name: 'Vector of Sickness IV',
    origCastTime: 0,
    recastTime: 0,
    resist: 'DISEASE',
    skill: 52,
    target: 'SINGLE',
    timer: 'VOSIV',
    type3Dmg: 0
  },
  WOC4: {
    base1: 100,
    baseDmg: 7200,
    castTime: 0,
    focusable: true,
    id: 'WOC4',
    level: 255,
    lockoutTime: 0,
    manaCost: 0,
    name: 'Wave of Corruption IV',
    origCastTime: 0,
    recastTime: 0,
    resist: 'CORRUPTION',
    skill: 52,
    target: 'SINGLE',
    timer: 'WOC4',
    type3Dmg: 0
  },
  WSYN: {
    baseDmg: 25000,
    castTime: 0,
    focusable: false,
    id: 'WSYN',
    level: 254,
    lockoutTime: 0,
    manaCost: 0,
    name: 'Evoker\'s Synergy Strike I',
    origCastTime: 0,
    recastTime: 0,
    resist: 'MAGIC',
    skill: 98,
    spellDmgCap: 0,
    target: 'SINGLE',
    timer: 'WSYN'
  }
}

// Dark Shield of the Scholar procs Force of Magic XV so use that for default
// settings
SPELL_DATA.DS = Object.assign({}, SPELL_DATA.FOMXV, {
  castTime: 100,
  id: 'DS',
  inventory: true,
  manaCost: 10, // twincast requires mana..
  name: 'Dark Shield of the Scholar',
  origCastTime: 100,
  skill: 52,
  target: 'SINGLE',
  timer: '3'
});