export const SPELL_DATA = {
  CA: {
    castTime: 1980,
    focusable: true,
    id: 'CA',
    level: 101,
    lockoutTime: 1500,
    manaCost:  	14194,
    name: 'Chromatic Alliance Rk. III',
    origCastTime: 3000,
    recastTime: 60000,
    resist: 'CHROMATIC',
    skill: 5,
    target: 'SINGLE',
    timer: '14'
  },
  CAF: {
    baseDmg: 2341541 ,
    castTime: 0,
    focusable: false,
    id: 'CAF',
    level: 255,
    lockoutTime: 0,
    manaCost: 0,
    max: 2696520,
    maxCritRate: 0,
    name: 'Chromatic Fulmination III',
    origCastTime: 0,
    recastTime: 0,
    resist: 'CHROMATIC',
    skill: 5,
    spellDmgCap: 0,
    target: 'SINGLE',
    timer: 'caf'
  },
  CD: {
    baseDmg: 0,
    castTime: 1750,
    focusable: false,
    id: 'CD',
    level: 108,
    lockoutTime: 1500,
    manaCost: 1495,
    mez: true,
    name: 'Chaotic Delusion Rk. III',
    origCastTime: 2500,
    recastTime: 1500,
    resist: 'MAGIC',
    skill: 14,
    target: 'SINGLE',
    timer: 'chaoticdelusion',
    type3Dmg: 0
  },
  CR: {
    baseDmg: 12940,
    castTime: 1500,
    focusable: true,
    id: 'CR',
    level: 107,
    lockoutTime: 1500,
    manaCost: 1427,
    name: 'Chromareave Rk. III',
    origCastTime: 3000,
    recastTime: 4500,
    resist: 'CHROMATIC',
    skill: 24,
    target: 'SINGLE',
    timer: 'chromareave',
    type3DmgAug: 924
  },
  DR: {
    baseDmg: 0,
    beneficial: true,
    castTime: 1500,
    focusable: false,
    id: 'DR',
    level: 101,
    lockoutTime: 1500,
    manaCost: 10458,
    name: 'Dichotomic Reinforcement 6',
    origCastTime: 3000,
    recastTime: 60000,
    resist: 'NONE',
    skill: 4,
    target: 'GROUP',
    timer: '13',
    type3Dmg: 0
  },
  GT: {
    baseDmg: 17482,
    castTime: 1950,
    focusable: true,
    id: 'GT',
    level: 104,
    lockoutTime: 1500,
    manaCost: 2746,
    name: 'Gravity Twist Rk. III',
    origCastTime: 3900,
    recastTime: 6000,
    resist: 'MAGIC',
    skill: 5,
    target: 'AE',
    timer: 'gtwist',
    type3DmgAug: 0
  },
  MC: {
    baseDmg: 22922,
    castTime: 2000,
    focusable: true,
    id: 'MC',
    level: 100,
    lockoutTime: 1500,
    manaCost: 3587,
    name: 'Mindcleave Rk. III',
    origCastTime: 4000,
    recastTime: 9000,
    resist: 'CHROMATIC',
    skill: 24,
    target: 'SINGLE',
    timer: 'mindcleave',
    type3DmgAug: 1537
  },
  MU: {
    baseDmg: 25271,
    castTime: 2000,
    focusable: true,
    id: 'MU',
    level: 110,
    lockoutTime: 1500,
    manaCost: 4112,
    name: 'Mindsunder Rk. III',
    origCastTime: 4000,
    recastTime: 9000,
    resist: 'CHROMATIC',
    skill: 24,
    target: 'SINGLE',
    timer: 'mindsunder',
    type3DmgAug: 1804
  },
  MS: {
    baseDmg: 30647,
    castTime: 2000,
    focusable: true,
    id: 'MS',
    level: 110,
    lockoutTime: 1500,
    manaCost: 4930,
    name: 'Mindslash Rk. III',
    origCastTime: 4000,
    recastTime: 9000,
    resist: 'CHROMATIC',
    skill: 24,
    target: 'SINGLE',
    timer: 'mindslash',
    type3DmgAug: 2189
  },
  PA: {
    baseDmg: 15103,
    castTime: 1500,
    focusable: true,
    id: 'PA',
    level: 108,
    lockoutTime: 1500,
    manaCost: 1630,
    name: 'Polyfluorescent Assault Rk. III',
    origCastTime: 3000,
    recastTime: 4500,
    resist: 'CHROMATIC',
    skill: 24,
    target: 'SINGLE',
    timer: 'polyflourescent',
    type3DmgAug: 1079
  }
};
