export const SPELL_DATA = {
  "TC": {
    "id": "TC",
    "name": "Twincast Rk. III",
    "baseDmg": 0,
    "castTime": 0,
    "origCastTime": 0,
    "recastTime": 300,
    "lockoutTime": 1.5,
    "resist": "NONE",
    "type3Dmg": 0,
    "target": "self",
    "canTwincast": false,
    "type": "beneficial",
    "timer": "twincast",
    "manaCost": 1,
    "skill": 4,
    "level": 85
  },
  "WSYN": {
    "id": "WSYN",
    "name": "Evoker's Synergy Strike I",
    "baseDmg": 25000,
    "castTime": 0.0,
    "origCastTime": 0.0,
    "recastTime": 0.0,
    "lockoutTime": 0.0,
    "resist": "MAGIC",
    "type3Aug": 0,
    "canTwincast": false,
    "timer": "WSYN",
    "manaCost": 0,
    "isZeroFocusable": true,
    "skill": 98,
    "level": 254,
    "requirements": {
      "spellCastOrEqpProc": true,
      "resists": ["MAGIC", "ICE", "DISEASE", "CORRUPTION", "CHROMATIC"]
    }    
  },
  "AB": {
    "id": "AB",
    "name": "Hedgewizard's Spell",
    "baseDmg": 6500,
    "castTime": 0.0,
    "origCastTime": 0.0,
    "recastTime": 0.0,
    "lockoutTime": 0.0,
    "resist": "DISEASE",
    "type3Dmg": 0,
    "canTwincast": false,
    "timer": "AB",
    "manaCost": 0,
    "base1": 100,
    "skill": 24,
    "level": 255,
    "requirements": {
      "minManaCost": 10,
      "minLevel": 75,
      "spellCastOnly": true
    }
  },
  "ASVI": {
    "id": "ASVI",
    "name": "Arcane Strike VI",
    "baseDmg": 225,
    "castTime": 0.0,
    "origCastTime": 0.0,
    "recastTime": 0.0,
    "lockoutTime": 0.0,
    "resist": "MAGIC",
    "type3Dmg": 0,
    "canTwincast": false,
    "timer": "ASVI",
    "manaCost": 0,
    "base1": 100,
    "spellDmgCap": 225,
    "level": 255,
    "skill": 52,
    "requirements": {
      "minLevel": 70,
      "minManaCost": 10,
      "spellCastOnly": true
    }
  },
  "BFVI": {
    "id": "BFVI",
    "name": "Blaze of Fire VI",
    "baseDmg": 10000,
    "castTime": 0.0,
    "origCastTime": 0.0,
    "recastTime": 0.0,
    "lockoutTime": 0.0,
    "resist": "FIRE",
    "type3Dmg": 0,
    "canTwincast": false,
    "timer": "BFVI",
    "manaCost": 0,
    "base1": 100,
    "skill": 52,
    "level": 255,
    "requirements": {
      "minLevel": 70,
      "minManaCost": 10,
      "spellCastOnly": true
    }
  },
  "BOIX": {
    "id": "BOIX",
    "name": "Burst of Ice X",
    "baseDmg": 1050,
    "castTime": 0.0,
    "origCastTime": 0.0,
    "recastTime": 0.0,
    "lockoutTime": 0.0,
    "resist": "ICE",
    "type3Dmg": 0,
    "canTwincast": false,
    "timer": "BOIX",
    "manaCost": 0,
    "base1": 100,
    "skill": 52,
    "level": 255,
    "requirements": {
      "minLevel": 70,
      "minManaCost": 10,
      "spellCastOnly": true
    }
  },
  "FCVII": {
    "id": "FCVII",
    "name": "Force of Corruption VII",
    "baseDmg": 540,
    "castTime": 0.0,
    "origCastTime": 0.0,
    "recastTime": 0.0,
    "lockoutTime": 0.0,
    "resist": "CORRUPTION",
    "type3Dmg": 0,
    "canTwincast": false,
    "timer": "FCVII",
    "manaCost": 0,
    "base1": 100,
    "skill": 52,
    "level": 255,
    "requirements": {
      "minLevel": 70,
      "minManaCost": 10,
      "spellCastOnly": true
    }
  },
  "FCX": {
    "id": "FCX",
    "name": "Force of Corruption X",
    "baseDmg": 945,
    "castTime": 0.0,
    "origCastTime": 0.0,
    "recastTime": 0.0,
    "lockoutTime": 0.0,
    "resist": "CORRUPTION",
    "type3Dmg": 0,
    "canTwincast": false,
    "timer": "FCX",
    "manaCost": 0,
    "base1": 100,
    "skill": 52,
    "level": 255,
    "requirements": {
      "minLevel": 70,
      "minManaCost": 10,
      "spellCastOnly": true
    }
  },
  "FOMVII": {
    "id": "FOMVII",
    "name": "Force of Magic VII",
    "baseDmg": 600,
    "castTime": 0.0,
    "origCastTime": 0.0,
    "recastTime": 0.0,
    "lockoutTime": 0.0,
    "resist": "MAGIC",
    "type3Dmg": 0,
    "canTwincast": false,
    "timer": "FOMVII",
    "manaCost": 0,
    "base1": 100,
    "skill": 52,
    "level": 255,
    "requirements": {
      "minLevel": 70,
      "minManaCost": 10,
      "spellCastOnly": true
    }
  },
  "FOMIX": {
    "id": "FOMIX",
    "name": "Force of Magic IX",
    "baseDmg": 900,
    "castTime": 0.0,
    "origCastTime": 0.0,
    "recastTime": 0.0,
    "lockoutTime": 0.0,
    "resist": "MAGIC",
    "type3Dmg": 0,
    "canTwincast": false,
    "timer": "FOMIX",
    "manaCost": 0,
    "base1": 100,
    "skill": 52,
    "level": 255,
    "requirements": {
      "minLevel": 70,
      "minManaCost": 10,
      "spellCastOnly": true
    }
  },
  "FOMXIII": {
    "id": "FOMXIII",
    "name": "Force of Magic XIII",
    "baseDmg": 1500,
    "castTime": 0.0,
    "origCastTime": 0.0,
    "recastTime": 0.0,
    "lockoutTime": 0.0,
    "resist": "MAGIC",
    "type3Dmg": 0,
    "canTwincast": false,
    "timer": "FOMXIII",
    "manaCost": 0,
    "base1": 100,
    "skill": 52,
    "level": 255,
    "requirements": {
      "minLevel": 70,
      "minManaCost": 10,
      "spellCastOnly": true
    }
  },
  "FOMXV": {
    "id": "FOMXV",
    "name": "Force of Magic XV",
    "baseDmg": 1800,
    "castTime": 0.0,
    "origCastTime": 0.0,
    "recastTime": 0.0,
    "lockoutTime": 0.0,
    "resist": "MAGIC",
    "type3Dmg": 0,
    "canTwincast": false,
    "timer": "FOMXV",
    "manaCost": 0,
    "base1": 100,
    "skill": 52,
    "level": 255,
    "requirements": {
      "minLevel": 70,
      "minManaCost": 10,
      "spellCastOnly": true
    }
  },
  "FSVI": {
    "id": "FSVI",
    "name": "Fiery Strike VI",
    "baseDmg": 225,
    "castTime": 0.0,
    "origCastTime": 0.0,
    "recastTime": 0.0,
    "lockoutTime": 0.0,
    "resist": "FIRE",
    "type3Dmg": 0,
    "canTwincast": false,
    "timer": "FSVI",
    "manaCost": 0,
    "base1": 100,
    "spellDmgCap": 225,
    "skill": 52,
    "level": 255,
    "requirements": {
      "minLevel": 70,
      "minManaCost": 10,
      "spellCastOnly": true
    }
  },
  "FSVII": {
    "id": "FSVII",
    "name": "Fiery Strike VII",
    "baseDmg": 250,
    "castTime": 0.0,
    "origCastTime": 0.0,
    "recastTime": 0.0,
    "lockoutTime": 0.0,
    "resist": "FIRE",
    "type3Dmg": 0,
    "canTwincast": false,
    "timer": "FSVII",
    "manaCost": 0,
    "base1": 100,
    "spellDmgCap": 250,
    "skill": 52,
    "level": 255,
    "requirements": {
      "minLevel": 70,
      "minManaCost": 10,
      "spellCastOnly": true
    }
  },
  "HOM3": {
    "id": "HOM3",
    "name": "Hammer of Magic III",
    "baseDmg": 7000,
    "castTime": 0.0,
    "origCastTime": 0.0,
    "recastTime": 0.0,
    "lockoutTime": 0.0,
    "resist": "MAGIC",
    "type3Dmg": 0,
    "canTwincast": false,
    "timer": "HOM3",
    "manaCost": 0,
    "base1": 100,
    "skill": 52,
    "level": 255,
    "requirements": {
      "minLevel": 70,
      "minManaCost": 10,
      "spellCastOnly": true
    }
  },  
  "OS": {
    "id": "OS",
    "name": "Obulous Strike",
    "baseDmg": 4000,
    "castTime": 0.0,
    "origCastTime": 0.0,
    "recastTime": 0.0,
    "lockoutTime": 0.0,
    "resist": "CHROMATIC",
    "type3Dmg": 0,
    "canTwincast": false,
    "timer": "OS",
    "manaCost": 0,
    "base1": 100,
    "skill": 52,
    "level": 255,
    "requirements": {
      "minLevel": 70,
      "minManaCost": 675,
      "spellCastOnly": true
    }
  },
  "SOFV": {
    "id": "SOFV",
    "name": "Strike of Flames V",
    "baseDmg": 420,
    "castTime": 0.0,
    "origCastTime": 0.0,
    "recastTime": 0.0,
    "lockoutTime": 0.0,
    "resist": "FIRE",
    "type3Dmg": 0,
    "canTwincast": false,
    "timer": "SOFV",
    "manaCost": 0,
    "base1": 100,
    "skill": 52,
    "level": 255,
    "requirements": {
      "minLevel": 70,
      "minManaCost": 10,
      "spellCastOnly": true
    }
  },
  "SOFXIII": {
    "id": "SOFXIII",
    "name": "Strike of Flames XIII",
    "baseDmg": 1500,
    "castTime": 0.0,
    "origCastTime": 0.0,
    "recastTime": 0.0,
    "lockoutTime": 0.0,
    "resist": "FIRE",
    "type3Dmg": 0,
    "canTwincast": false,
    "timer": "SOFXIII",
    "manaCost": 0,
    "base1": 100,
    "skill": 52,
    "level": 255,
    "requirements": {
      "minLevel": 70,
      "minManaCost": 10,
      "spellCastOnly": true
    }
  },
  "SOFXIV": {
    "id": "SOFXIV",
    "name": "Strike of Flames XIV",
    "baseDmg": 1650,
    "castTime": 0.0,
    "origCastTime": 0.0,
    "recastTime": 0.0,
    "lockoutTime": 0.0,
    "resist": "FIRE",
    "type3Dmg": 0,
    "canTwincast": false,
    "timer": "SOFXIV",
    "manaCost": 0,
    "base1": 100,
    "skill": 52,
    "level": 255,
    "requirements": {
      "minLevel": 70,
      "minManaCost": 10,
      "spellCastOnly": true
    }
  },
  "VOSIV": {
    "id": "VOSIV",
    "name": "Vector of Sickness IV",
    "baseDmg": 3200,
    "castTime": 0.0,
    "origCastTime": 0.0,
    "recastTime": 0.0,
    "lockoutTime": 0.0,
    "resist": "DISEASE",
    "type3Dmg": 0,
    "canTwincast": false,
    "timer": "VOSIV",
    "manaCost": 0,
    "base1": 100,
    "skill": 52,
    "level": 255,
    "requirements": {
      "minLevel": 70,
      "minManaCost": 10,
      "spellCastOnly": true
    }
  },
  "WOC4": {
    "id": "WOC4",
    "name": "Wave of Corruption IV",
    "baseDmg": 7200,
    "castTime": 0.0,
    "origCastTime": 0.0,
    "recastTime": 0.0,
    "lockoutTime": 0.0,
    "resist": "CORRUPTION",
    "type3Dmg": 0,
    "canTwincast": false,
    "timer": "WOC4",
    "manaCost": 0,
    "base1": 100,
    "skill": 52,
    "level": 255,
    "requirements": {
      "minLevel": 70,
      "minManaCost": 10,
      "spellCastOnly": true
    }
  },
  "FW": {
    "id": "FW",
    "name": "Frostweave Strike III",
    "baseDmg": 3365,
    "castTime": 0.0,
    "origCastTime": 0.0,
    "recastTime": 0.0,
    "lockoutTime": 0.0,
    "resist": "ICE",
    "type3Dmg": 0,
    "canTwincast": false,
    "timer": "FW",
    "manaCost": 0,
    "skill": 24,
    "level": 255,
    "requirements": {
      "minManaCost": 10,
      "maxLevel": 110,
      "spellCastOnly": true
    }
  },
  "DRS6": {
    "id": "DRS6",
    "name": "Dichotomic Reinforced Strike 6",
    "baseDmg": 21944,
    "castTime": 0.0,
    "origCastTime": 0.0,
    "recastTime": 6.0,
    "lockoutTime": 0.0,
    "resist": "CHROMATIC",
    "type3Dmg": 0,
    "canTwincast": false,
    "timer": "DRS6",
    "manaCost": 0,
    "base1": 160,
    "skill": 24,
    "level": 255,
    "requirements": {
      "minManaCost": 100,
      "maxLevel": 110,
      "spellCastOnly": true
    }
  },
  "MR": {
    "id": "MR",
    "name": "Mana Reciprocation Strike III",
    "baseDmg": 4137,
    "castTime": 0.0,
    "origCastTime": 0.0,
    "recastTime": 0.0,
    "lockoutTime": 0.0,
    "resist": "CHROMATIC",
    "type3Dmg": 0,
    "canTwincast": false,
    "timer": "MRR",
    "manaCost": 0,
    "skill": 5,
    "level": 255,
    "requirements": {
      "minManaCost": 10,
      "maxLevel": 105,
      "spellCastOnly": true
    }
  },
  "MRR": {
    "id": "MRR",
    "name": "Mana Re-Reciprocation Strike III",
    "baseDmg": 4551,
    "castTime": 0.0,
    "origCastTime": 0.0,
    "recastTime": 0.0,
    "lockoutTime": 0.0,
    "resist": "CHROMATIC",
    "type3Dmg": 0,
    "canTwincast": false,
    "timer": "MRR",
    "manaCost": 0,
    "skill": 5,
    "level": 255
  },
  "MRRR": {
    "id": "MRRR",
    "name": "Mana Re-Reciprocation Strike III",
    "baseDmg": 5006,
    "castTime": 0.0,
    "origCastTime": 0.0,
    "recastTime": 0.0,
    "lockoutTime": 0.0,
    "resist": "CHROMATIC",
    "type3Dmg": 0,
    "canTwincast": false,
    "timer": "MRRR",
    "manaCost": 0,
    "skill": 5,
    "level": 255
  },
  "MRRRR": {
    "id": "MRRRR",
    "name": "Mana Re-Reciprocation Strike III",
    "baseDmg": 5507,
    "castTime": 0.0,
    "origCastTime": 0.0,
    "recastTime": 0.0,
    "lockoutTime": 0.0,
    "resist": "CHROMATIC",
    "type3Dmg": 0,
    "canTwincast": false,
    "timer": "MRRRR",
    "manaCost": 0,
    "skill": 5,
    "level": 255
  }
};