export const SPELL_DATA = {
  TC: {
    id: 'TC',
    name: 'Twincast Rk. III',
    beneficial: true,
    baseDmg: 0,
    castTime: 0,
    origCastTime: 0,
    recastTime: 300000,
    lockoutTime: 1500,
    resist: 'NONE',
    type3Dmg: 0,
    target: 'self',
    timer: 'twincast',
    manaCost: 1,
    focusable: false,
    skill: 4,
    level: 85
  },
  AHB: {
    id: 'AHB',
    name: 'Hedgewizard\'s Spell',
    baseDmg: 6500,
    castTime: 0,
    origCastTime: 0,
    recastTime: 0,
    lockoutTime: 0,
    resist: 'DISEASE',
    type3Dmg: 0,
    timer: 'AB',
    manaCost: 0,
    max: 0,
    base1: 100,
    focusable: false,
    skill: 24,
    level: 255
  },
  AM: {
    id: 'AM',
    name: 'Arcane Melody Effect III',
    baseDmg: 1206,
    castTime: 0,
    origCastTime: 0,
    recastTime: 0,
    lockoutTime: 0,
    resist: 'MAGIC',
    type3Dmg: 0,
    timer: 'AM',
    manaCost: 0,
    focusable: true,
    skill: 98,
    level: 255
  },
  ASVI: {
    id: 'ASVI',
    name: 'Arcane Strike VI',
    baseDmg: 225,
    castTime: 0,
    origCastTime: 0,
    recastTime: 0,
    lockoutTime: 0,
    resist: 'MAGIC',
    type3Dmg: 0,
    timer: 'ASVI',
    manaCost: 0,
    base1: 100,
    spellDmgCap: 225,
    level: 255,
    focusable: true,
    skill: 52
  },
  BFVI: {
    id: 'BFVI',
    name: 'Blaze of Fire VI',
    baseDmg: 10000,
    castTime: 0,
    origCastTime: 0,
    recastTime: 0,
    lockoutTime: 0,
    resist: 'FIRE',
    type3Dmg: 0,
    timer: 'BFVI',
    manaCost: 0,
    base1: 100,
    focusable: true,
    skill: 52,
    level: 255
  },
  BOIX: {
    id: 'BOIX',
    name: 'Burst of Ice X',
    baseDmg: 1050,
    castTime: 0,
    origCastTime: 0,
    recastTime: 0,
    lockoutTime: 0,
    resist: 'COLD',
    type3Dmg: 0,
    timer: 'BOIX',
    manaCost: 0,
    base1: 100,
    focusable: true,
    skill: 52,
    level: 255
  },
  FCVII: {
    id: 'FCVII',
    name: 'Force of Corruption VII',
    baseDmg: 540,
    castTime: 0,
    origCastTime: 0,
    recastTime: 0,
    lockoutTime: 0,
    resist: 'CORRUPTION',
    type3Dmg: 0,
    timer: 'FCVII',
    manaCost: 0,
    base1: 100,
    focusable: true,
    skill: 52,
    level: 255
  },
  FCX: {
    id: 'FCX',
    name: 'Force of Corruption X',
    baseDmg: 945,
    castTime: 0,
    origCastTime: 0,
    recastTime: 0,
    lockoutTime: 0,
    resist: 'CORRUPTION',
    type3Dmg: 0,
    timer: 'FCX',
    manaCost: 0,
    base1: 100,
    focusable: true,
    skill: 52,
    level: 255
  },
  FOMVII: {
    id: 'FOMVII',
    name: 'Force of Magic VII',
    baseDmg: 600,
    castTime: 0,
    origCastTime: 0,
    recastTime: 0,
    lockoutTime: 0,
    resist: 'MAGIC',
    type3Dmg: 0,
    timer: 'FOMVII',
    manaCost: 0,
    base1: 100,
    focusable: true,
    skill: 52,
    level: 255
  },
  FOMIX: {
    id: 'FOMIX',
    name: 'Force of Magic IX',
    baseDmg: 900,
    castTime: 0,
    origCastTime: 0,
    recastTime: 0,
    lockoutTime: 0,
    resist: 'MAGIC',
    type3Dmg: 0,
    timer: 'FOMIX',
    manaCost: 0,
    base1: 100,
    focusable: true,
    skill: 52,
    level: 255
  },
  FOMXIII: {
    id: 'FOMXIII',
    name: 'Force of Magic XIII',
    baseDmg: 1500,
    castTime: 0,
    origCastTime: 0,
    recastTime: 0,
    lockoutTime: 0,
    resist: 'MAGIC',
    type3Dmg: 0,
    timer: 'FOMXIII',
    manaCost: 0,
    base1: 100,
    focusable: true,
    skill: 52,
    level: 255
  },
  FOMXV: {
    id: 'FOMXV',
    name: 'Force of Magic XV',
    baseDmg: 1800,
    castTime: 0,
    origCastTime: 0,
    recastTime: 0,
    lockoutTime: 0,
    resist: 'MAGIC',
    type3Dmg: 0,
    timer: 'FOMXV',
    manaCost: 0,
    base1: 100,
    focusable: true,
    skill: 52,
    level: 255
  },
  FSVI: {
    id: 'FSVI',
    name: 'Fiery Strike VI',
    baseDmg: 225,
    castTime: 0,
    origCastTime: 0,
    recastTime: 0,
    lockoutTime: 0,
    resist: 'FIRE',
    type3Dmg: 0,
    timer: 'FSVI',
    manaCost: 0,
    base1: 100,
    spellDmgCap: 225,
    focusable: true,
    skill: 52,
    level: 255
  },
  FSVII: {
    id: 'FSVII',
    name: 'Fiery Strike VII',
    baseDmg: 250,
    castTime: 0,
    origCastTime: 0,
    recastTime: 0,
    lockoutTime: 0,
    resist: 'FIRE',
    type3Dmg: 0,
    timer: 'FSVII',
    manaCost: 0,
    base1: 100,
    spellDmgCap: 250,
    focusable: true,
    skill: 52,
    level: 255
  },
  HOM3: {
    id: 'HOM3',
    name: 'Hammer of Magic III',
    baseDmg: 7000,
    castTime: 0,
    origCastTime: 0,
    recastTime: 0,
    lockoutTime: 0,
    resist: 'MAGIC',
    type3Dmg: 0,
    timer: 'HOM3',
    manaCost: 0,
    base1: 100,
    focusable: true,
    skill: 52,
    level: 255
  },
  OS: {
    id: 'OS',
    name: 'Obulus Strike',
    baseDmg: 4000,
    castTime: 0,
    origCastTime: 0,
    recastTime: 0,
    lockoutTime: 0,
    resist: 'CHROMATIC',
    type3Dmg: 0,
    timer: 'OS',
    manaCost: 0,
    base1: 100,
    focusable: false,
    skill: 52,
    level: 255,
    requirements: {
      minLevel: 70,
      minManaCost: 675,
      canProcSpells: true
    }
  },
  SOFV: {
    id: 'SOFV',
    name: 'Strike of Flames V',
    baseDmg: 420,
    castTime: 0,
    origCastTime: 0,
    recastTime: 0,
    lockoutTime: 0,
    resist: 'FIRE',
    type3Dmg: 0,
    timer: 'SOFV',
    manaCost: 0,
    base1: 100,
    focusable: true,
    skill: 52,
    level: 255
  },
  SOFXIII: {
    id: 'SOFXIII',
    name: 'Strike of Flames XIII',
    baseDmg: 1500,
    castTime: 0,
    origCastTime: 0,
    recastTime: 0,
    lockoutTime: 0,
    resist: 'FIRE',
    type3Dmg: 0,
    timer: 'SOFXIII',
    manaCost: 0,
    base1: 100,
    focusable: true,
    skill: 52,
    level: 255
  },
  SOFXIV: {
    id: 'SOFXIV',
    name: 'Strike of Flames XIV',
    baseDmg: 1650,
    castTime: 0,
    origCastTime: 0,
    recastTime: 0,
    lockoutTime: 0,
    resist: 'FIRE',
    type3Dmg: 0,
    timer: 'SOFXIV',
    manaCost: 0,
    base1: 100,
    focusable: true,
    skill: 52,
    level: 255
  },
  VOSIV: {
    id: 'VOSIV',
    name: 'Vector of Sickness IV',
    baseDmg: 3200,
    castTime: 0,
    origCastTime: 0,
    recastTime: 0,
    lockoutTime: 0,
    resist: 'DISEASE',
    type3Dmg: 0,
    timer: 'VOSIV',
    manaCost: 0,
    base1: 100,
    focusable: true,
    skill: 52,
    level: 255
  },
  WOC4: {
    id: 'WOC4',
    name: 'Wave of Corruption IV',
    baseDmg: 7200,
    castTime: 0,
    origCastTime: 0,
    recastTime: 0,
    lockoutTime: 0,
    resist: 'CORRUPTION',
    type3Dmg: 0,
    timer: 'WOC4',
    manaCost: 0,
    base1: 100,
    focusable: true,
    skill: 52,
    level: 255
  },
  FW: {
    id: 'FW',
    name: 'Frostweave Strike III',
    baseDmg: 3365,
    castTime: 0,
    origCastTime: 0,
    recastTime: 0,
    lockoutTime: 0,
    resist: 'COLD',
    type3Dmg: 0,
    timer: 'FW',
    manaCost: 0,
    focusable: true,
    skill: 24,
    level: 255
  },
  DR: {
    id: 'DR',
    name: 'Dichotomic Reinforced Strike 6',
    baseDmg: 21944,
    castTime: 0,
    origCastTime: 0,
    recastTime: 6000,
    lockoutTime: 0,
    resist: 'CHROMATIC',
    type3Dmg: 0,
    timer: 'DR',
    manaCost: 0,
    base1: 160,
    focusable: true,
    skill: 24,
    level: 255
  },
  MR: {
    id: 'MR',
    name: 'Mana Reciprocation Strike III',
    baseDmg: 4137,
    castTime: 0,
    origCastTime: 0,
    recastTime: 0,
    lockoutTime: 0,
    resist: 'CHROMATIC',
    type3Dmg: 0,
    timer: 'MRR',
    max: 0,
    manaCost: 0,
    focusable: true,
    skill: 5,
    level: 255
  },
  MRR: {
    id: 'MRR',
    name: 'Mana Re-Reciprocation Strike III',
    baseDmg: 4551,
    castTime: 0,
    origCastTime: 0,
    recastTime: 0,
    lockoutTime: 0,
    resist: 'CHROMATIC',
    type3Dmg: 0,
    timer: 'MRR',
    max: 0,
    manaCost: 0,
    focusable: true,
    skill: 5,
    level: 255
  },
  MRRR: {
    id: 'MRRR',
    name: 'Mana Re-Re-Reciprocation Strike III',
    baseDmg: 5006,
    castTime: 0,
    origCastTime: 0,
    recastTime: 0,
    lockoutTime: 0,
    resist: 'CHROMATIC',
    type3Dmg: 0,
    timer: 'MRRR',
    max: 0,
    manaCost: 0,
    focusable: true,
    skill: 5,
    level: 255
  },
  MRRRR: {
    id: 'MRRRR',
    name: 'Mana Re-Re-Re-Reciprocation Strike III',
    baseDmg: 5507,
    castTime: 0,
    origCastTime: 0,
    recastTime: 0,
    lockoutTime: 0,
    resist: 'CHROMATIC',
    type3Dmg: 0,
    timer: 'MRRRR',
    max: 0,
    manaCost: 0,
    focusable: true,
    skill: 5,
    level: 255
  },
  WSYN: {
    id: 'WSYN',
    name: 'Evoker\'s Synergy Strike I',
    baseDmg: 25000,
    castTime: 0,
    origCastTime: 0,
    recastTime: 0,
    lockoutTime: 0,
    resist: 'MAGIC',
    timer: 'WSYN',
    manaCost: 0,
    spellDmgCap: 0,
    focusable: false,
    skill: 98,
    level: 254
  }
};

// Dark Shield of the Scholar procs Force of Magic XV so use that for default settings
SPELL_DATA.DS = Object.assign(
  {},
  SPELL_DATA.FOMXV,
  {
    id: 'DS',
    name: 'Dark Shield of the Scholar',
    castTime: 100,
    origCastTime: 100,
    timer: '3',
    discRefresh: 10000,
    manaCost: 10
  }
);