export const SPELL_DATA = {
  AFU1: {
    base1: 10,
    baseDmg: 73450,
    castTime: 0,
    focusable: false,
    id: 'AFU1',
    level: 254,
    manaCost: 0,
    maxCritRate: 0.15,
    name: 'Arcane Fusion I',
    origCastTime: 0,
    recastTime: 0,
    resist: 'MAGIC',
    skill: 24,
    target: 'SINGLE',
    timer: 'afusion'
  },
  AFU2: {
    base1: 10,
    baseDmg: 100000,
    castTime: 0,
    focusable: false,
    id: 'AFU2',
    level: 254,
    manaCost: 0,
    maxCritRate: 0.15,
    name: 'Arcane Fusion II',
    origCastTime: 0,
    recastTime: 0,
    resist: 'MAGIC',
    skill: 24,
    target: 'SINGLE',
    timer: 'afusion'
  },
  AFU3: {
    base1: 10,
    baseDmg: 150000,
    castTime: 0,
    focusable: false,
    id: 'AFU3',
    level: 254,
    manaCost: 0,
    maxCritRate: 0.15,
    name: 'Arcane Fusion III',
    origCastTime: 0,
    recastTime: 0,
    resist: 'MAGIC',
    skill: 24,
    target: 'SINGLE',
    timer: 'afusion'
  },
  CRYO: {
    baseDmg: 21050,
    castTime: 0,
    focusable: false,
    id: 'CRYO',
    level: 254,
    manaCost: 0,
    name: 'Cryomantic Stasis XXVII (Not In Beta Yet)',
    origCastTime: 0,
    recastTime: 0,
    resist: 'COLD',
    skill: 5,
    target: 'SINGLE',
    timer: 'cryo'
  },
  CQ: {
    baseDmg: 26276,
    castTime: 1500,
    focusable: true,
    id: 'CQ',
    level: 108,
    lockoutTime: 1500,
    manaCost: 2014,
    name: 'Claw of Qunard Rk. III',
    origCastTime: 3000,
    recastTime: 6000,
    resist: 'FIRE',
    skill: 24,
    target: 'SINGLE',
    timer: '11',
    type3DmgAug: 0
  },
  CI: {
    baseDmg: 7237,
    castTime: 600,
    focusable: true,
    id: 'CI',
    level: 99,
    lockoutTime: 1500,
    manaCost: 714,
    name: 'Chaos Incandescence Rk. III',
    origCastTime: 750,
    recastTime: 4000,
    resist: 'FIRE',
    skill: 24,
    target: 'SINGLE',
    timer: 'chaosinc',
    type3DmgAug: 673
  },
  CO: {
    baseDmg: 23631,
    castTime: 1500,
    focusable: true,
    id: 'CO',
    level: 110,
    lockoutTime: 1500,
    manaCost: 1812,
    name: 'Claw of Travenro Rk. III',
    origCastTime: 3000,
    recastTime: 6000,
    resist: 'COLD',
    skill: 24,
    target: 'SINGLE',
    timer: '11',
    type3DmgAug: 0
  },
  CB: {
    baseDmg: 10577,
    canTwincast: false,
    castTime: 0,
    focusable: true,
    id: 'CB',
    level: 106,
    lockoutTime: 1500,
    manaCost: 100,
    name: 'Chaos Burn III',
    origCastTime: 0,
    recastTime: 4750,
    resist: 'FIRE',
    skill: 24,
    target: 'SINGLE',
    timer: 'chaosburn',
    type3DmgAug: 0
  },
  CT: {
    baseDmg: 21765,
    castTime: 0,
    focusable: true,
    id: 'CT',
    level: 107,
    lockoutTime: 1500,
    manaCost: 3699,
    name: 'Cloudburst Thunderbolt Rk. III',
    origCastTime: 0,
    recastTime: 3000,
    resist: 'MAGIC',
    skill: 24,
    target: 'SINGLE',
    timer: '2',
    type3DmgAug: 0
  },
  DF: {
    baseDmg: 127710,
    canTwincast: false,
    castTime: 2000,
    focusable: true,
    id: 'DF',
    level: 250,
    lockoutTime: 1500,
    manaCost: 100,
    name: 'Dichotomic Fire 6',
    origCastTime: 0,
    recastTime: 60000,
    recastTime2: 6000,
    resist: 'FIRE',
    skill: 24,
    target: 'SINGLE',
    timer: 'dicho'
  },
  EI: {
    baseDmg: 36353,
    castTime: 1900,
    focusable: true,
    id: 'EI',
    level: 109,
    lockoutTime: 1500,
    manaCost: 5573,
    name: 'Ethereal Icefloe Rk. III',
    origCastTime: 3750,
    recastTime: 5250,
    resist: 'COLD',
    skill: 24,
    target: 'SINGLE',
    timer: 'eiceflow',
    type3DmgAug: 0
  },
  ES: {
    baseDmg: 40421,
    castTime: 1900,
    focusable: true,
    id: 'ES',
    level: 110,
    lockoutTime: 1500,
    manaCost: 6196,
    name: 'Ethereal Skyfire Rk. III',
    origCastTime: 3750,
    recastTime: 5500,
    resist: 'FIRE',
    skill: 24,
    target: 'SINGLE',
    timer: 'neskyblaze',
    type3DmgAug: 0
  },
  EV: {
    baseDmg: 34201,
    castTime: 1900,
    focusable: true,
    id: 'EV',
    level: 107,
    lockoutTime: 1500,
    manaCost: 5983,
    name: 'Ethereal Volley Rk. III',
    origCastTime: 3750,
    recastTime: 5500,
    resist: 'MAGIC',
    skill: 24,
    target: 'SINGLE',
    timer: 'evolley',
    type3DmgAug: 0
  },
  FA: {
    castTime: 2000,
    focusable: true,
    id: 'FA',
    level: 102,
    lockoutTime: 1500,
    manaCost: 13261,
    name: 'Frostbound Alliance Rk. III',
    origCastTime: 3000,
    recastTime: 60000,
    resist: 'COLD',
    skill: 5,
    target: 'SINGLE',
    timer: '14'
  },
  FAF: {
    baseDmg: 2696520,
    castTime: 0,
    focusable: false,
    id: 'FAF',
    level: 255,
    lockoutTime: 0,
    manaCost: 0,
    max: 2696520,
    maxCritRate: 0,
    name: 'Frostbound Fulmination III',
    origCastTime: 0,
    recastTime: 0,
    resist: 'COLD',
    skill: 5,
    spellDmgCap: 0,
    target: 'SINGLE',
    timer: 'ff'
  },
  FB: {
    baseDmg: 18547,
    castTime: 0,
    focusable: true,
    id: 'FB',
    level: 104,
    lockoutTime: 1500,
    manaCost: 2964,
    name: 'Flashburn Rk. III',
    origCastTime: 0,
    recastTime: 8250,
    resist: 'FIRE',
    skill: 24,
    target: 'SINGLE',
    timer: '2',
    type3DmgAug: 0
  },
  FF4: {
    aa: true,
    baseDmg: 14010,
    castTime: 500,
    focusable: false,
    id: 'FF4',
    level: 254,
    lockoutTime: 0,
    manaCost: 1750,
    name: 'Force of Flame IV',
    origCastTime: 500,
    recastTime: 0,
    resist: 'FIRE',
    skill: 24,
    target: 'SINGLE',
    timer: '36'
  },
  FF5: {
    aa: true,
    baseDmg: 15000,
    castTime: 500,
    focusable: false,
    id: 'FF5',
    level: 254,
    lockoutTime: 0,
    manaCost: 1750,
    name: 'Force of Flame V',
    origCastTime: 500,
    recastTime: 0,
    resist: 'FIRE',
    skill: 24,
    target: 'SINGLE',
    timer: '36'
  },
  FF6: {
    aa: true,
    baseDmg: 15985,
    castTime: 500,
    focusable: false,
    id: 'FF6',
    level: 254,
    lockoutTime: 0,
    manaCost: 1750,
    name: 'Force of Flame VI',
    origCastTime: 500,
    recastTime: 0,
    resist: 'FIRE',
    skill: 24,
    target: 'SINGLE',
    timer: '36'
  },
  FI4: {
    aa: true,
    baseDmg: 14010,
    castTime: 500,
    focusable: false,
    id: 'FI4',
    level: 254,
    lockoutTime: 0,
    manaCost: 1750,
    name: 'Force of Ice IV',
    origCastTime: 500,
    recastTime: 0,
    resist: 'COLD',
    skill: 24,
    target: 'SINGLE',
    timer: '44'
  },
  FI5: {
    aa: true,
    baseDmg: 15000,
    castTime: 500,
    focusable: false,
    id: 'FI5',
    level: 254,
    lockoutTime: 0,
    manaCost: 1750,
    name: 'Force of Ice V',
    origCastTime: 500,
    recastTime: 0,
    resist: 'COLD',
    skill: 24,
    target: 'SINGLE',
    timer: '44'
  },
  FI6: {
    aa: true,
    baseDmg: 15985,
    castTime: 500,
    focusable: false,
    id: 'FI6',
    level: 254,
    lockoutTime: 0,
    manaCost: 1750,
    name: 'Force of Ice VI',
    origCastTime: 500,
    recastTime: 0,
    resist: 'COLD',
    skill: 24,
    target: 'SINGLE',
    timer: '44'
  },
  EB: {
    castTime: 1500,
    focusable: true,
    id: 'EB',
    level: 110,
    lockoutTime: 1500,
    manaCost: 567,
    name: 'Ethereal Braid',
    origCastTime: 3000,
    recastTime: 36000,
    skill: 24,
    target: 'SINGLE',
    timer: '12'
  },
  FW24: {
    aa: true,
    baseDmg: 14010,
    castTime: 500,
    focusable: false,
    id: 'FW24',
    level: 254,
    lockoutTime: 0,
    manaCost: 1750,
    name: 'Force of Will XVI',
    origCastTime: 500,
    recastTime: 0,
    resist: 'MAGIC',
    skill: 24,
    target: 'SINGLE',
    timer: '37'
  },
  FW25: {
    aa: true,
    baseDmg: 15000,
    castTime: 500,
    focusable: false,
    id: 'FW25',
    level: 254,
    lockoutTime: 0,
    manaCost: 1750,
    name: 'Force of Will XVII',
    origCastTime: 500,
    recastTime: 0,
    resist: 'MAGIC',
    skill: 24,
    target: 'SINGLE',
    timer: '37'
  },
  FW26: {
    aa: true,
    baseDmg: 15985,
    castTime: 500,
    focusable: false,
    id: 'FW26',
    level: 254,
    lockoutTime: 0,
    manaCost: 1750,
    name: 'Force of Will XVIII',
    origCastTime: 500,
    recastTime: 0,
    resist: 'MAGIC',
    skill: 24,
    target: 'SINGLE',
    timer: '37'
  },
  HC: {
    baseDmg: 19104,
    castTime: 1500,
    focusable: true,
    id: 'HC',
    level: 99,
    lockoutTime: 1500,
    manaCost: 1964,
    name: 'Hoarfrost Cascade Rk. III',
    origCastTime: 3000,
    recastTime: 6000,
    resist: 'COLD',
    skill: 24,
    target: 'SINGLE',
    timer: 'hoarcascade',
    type3DmgAug: 1345
  },
  ME: {
    baseDmg: 16294,
    castTime: 1500,
    focusable: true,
    id: 'ME',
    level: 109,
    lockoutTime: 1500,
    manaCost: 2019,
    maxCritRate: 0.40,
    name: 'Magmatic Explosion Rk. III',
    origCastTime: 3000,
    recastTime: 12000,
    resist: 'FIRE',
    skill: 24,
    target: 'AE',
    timer: '6',
    type3DmgAug: 0
  },
  MBRN: {
    baseDmg: 2400000,
    castTime: 3000,
    focusable: false,
    id: 'MBRN',
    level: 254,
    lockoutTime: 0,
    manaCost: 60000,
    maxCritRate: 0,
    name: 'Mana Burn XVI',
    origCastTime: 3000,
    recastTime: 1800,
    resist: 'MAGIC',
    skill: 98,
    spellDmgCap: 0,
    target: 'SINGLE',
    timer: 'MBRN'
  },
  PE: {
    baseDmg: 11272,
    castTime: 600,
    focusable: true,
    id: 'PE',
    level: 100,
    lockoutTime: 1500,
    manaCost: 50,
    name: 'Pure Wildether III',
    origCastTime: 750,
    recastTime: 4000,
    resist: 'MAGIC',
    skill: 24,
    target: 'SINGLE',
    timer: 'pwildether',
    type3DmgAug: 794
  },
  PF: {
    baseDmg: 15826,
    canTwincast: false,
    castTime: 750,
    focusable: true,
    id: 'PF',
    level: 105,
    lockoutTime: 1500,
    manaCost: 50,
    name: 'Pure Wildflash Caza',
    origCastTime: 750,
    recastTime: 4000,
    resist: 'MAGIC',
    skill: 24,
    target: 'SINGLE',
    timer: 'pwildflash',
    type3DmgAug: 0
  },
  IC: {
    baseDmg: 25542 ,
    canTwincast: false,
    castTime: 0,
    focusable: true,
    id: 'IC',
    level: 106,
    lockoutTime: 1500,
    manaCost: 100,
    name: 'Icefloe Cascade III',
    origCastTime: 0,
    recastTime: 9000,
    resist: 'COLD',
    skill: 24,
    target: 'SINGLE',
    timer: 'iceflowcas',
    type3DmgAug: 0
  },
  SV: {
    baseDmg: 14388,
    castTime: 800,
    focusable: true,
    id: 'SV',
    level: 103,
    lockoutTime: 1500,
    manaCost: 1246,
    name: 'Shocking Vortex Rk. III',
    origCastTime: 1000,
    recastTime: 24000,
    resist: 'MAGIC',
    skill: 24,
    target: 'SINGLE',
    timer: 'vortex'
  },
  TW: {
    baseDmg: 24343,
    castTime: 1800,
    focusable: true,
    id: 'TW',
    level: 110,
    lockoutTime: 1500,
    manaCost: 2455,
    name: 'Thricewoven Capacity Rk. III',
    origCastTime: 3500,
    recastTime: 5000,
    resist: 'MAGIC',
    skill: 24,
    target: 'SINGLE',
    timer: 'thricecapacity',
    type3DmgAug: 0
  },
  WE: {
    baseDmg: 0,
    castTime: 600,
    focusable: true,
    id: 'WE',
    level: 96,
    lockoutTime: 1500,
    manaCost: 583,
    name: 'Wildether Barrage Rk. III',
    origCastTime: 750,
    recastTime: 4000,
    resist: 'MAGIC',
    skill: 24,
    target: 'SINGLE',
    timer: 'wildether'
  },
  WF: {
    baseDmg: 0,
    castTime: 600,
    focusable: true,
    id: 'WF',
    level: 106,
    lockoutTime: 1500,
    manaCost: 669,
    name: 'Wildflash Strike Rk. III',
    origCastTime: 750,
    recastTime: 4000,
    resist: 'MAGIC',
    skill: 24,
    target: 'SINGLE',
    timer: 'wildflash'
  }
};
