export const SPELL_DATA = {
  AFU1: {
    base1: 10,
    baseDmg: 73450,
    castTime: 0,
    focusable: false,
    id: 'AFU1',
    level: 254,
    manaCost: 0,
    maxCritRate: 0.15,
    name: 'Arcane Fusion I',
    origCastTime: 0,
    recastTime: 0,
    resist: 'MAGIC',
    skill: 24,
    target: 'SINGLE',
    timer: 'afusion'
  },
  AFU2: {
    base1: 10,
    baseDmg: 100000,
    castTime: 0,
    focusable: false,
    id: 'AFU2',
    level: 254,
    manaCost: 0,
    maxCritRate: 0.15,
    name: 'Arcane Fusion II',
    origCastTime: 0,
    recastTime: 0,
    resist: 'MAGIC',
    skill: 24,
    target: 'SINGLE',
    timer: 'afusion'
  },
  AFU3: {
    base1: 10,
    baseDmg: 150000,
    castTime: 0,
    focusable: false,
    id: 'AFU3',
    level: 254,
    manaCost: 0,
    maxCritRate: 0.15,
    name: 'Arcane Fusion III',
    origCastTime: 0,
    recastTime: 0,
    resist: 'MAGIC',
    skill: 24,
    target: 'SINGLE',
    timer: 'afusion'
  },
  AFU4: {
    base1: 10,
    baseDmg: 200000,
    castTime: 0,
    focusable: false,
    id: 'AFU4',
    level: 254,
    manaCost: 0,
    maxCritRate: 0.15,
    name: 'Arcane Fusion IV',
    origCastTime: 0,
    recastTime: 0,
    resist: 'MAGIC',
    skill: 24,
    target: 'SINGLE',
    timer: 'afusion'
  },
  BB: {
    baseDmg: 20299,
    castTime: 0,
    focusable: true,
    id: 'BB',
    level: 106,
    lockoutTime: 1500,
    manaCost: 2484 ,
    maxHits: 12,
    name: 'Burning Beam Rk. III',
    origCastTime: 0,
    recastTime: 12000,
    resist: 'FIRE',
    skill: 24,
    target: 'FrontalAE',
    timer: '2'
  },
  BBRk1: {
    baseDmg: 18411,
    name: 'Burning Beam Rk. I'
  },
  BBRk2: {
    baseDmg: 19332,
    name: 'Burning Beam Rk. II'
  },
  BBRk3: {
    baseDmg: 20299,
    name: 'Burning Beam Rk. III'
  },
  CRYO: {
    baseDmg: 25000,
    castTime: 0,
    focusable: false,
    id: 'CRYO',
    level: 254,
    manaCost: 0,
    name: 'Cryomantic Stasis XXVII',
    origCastTime: 0,
    recastTime: 0,
    resist: 'COLD',
    skill: 5,
    target: 'SINGLE',
    timer: 'cryo'
  },
  CQ: {
    baseDmg: 26276,
    castTime: 1500,
    focusable: true,
    id: 'CQ',
    level: 108,
    lockoutTime: 1500,
    manaCost: 2014,
    name: 'Claw of Qunard Rk. III',
    origCastTime: 3000,
    recastTime: 6000,
    resist: 'FIRE',
    skill: 24,
    target: 'SINGLE',
    timer: '11',
    type3DmgAug: 1688
  },
  CQRk1: {
    baseDmg: 23833,
    name: 'Claw of Qunard Rk. I'
  },
  CQRk2: {
    baseDmg: 25025,
    name: 'Claw of Qunard Rk. II'
  },
  CQRk3: {
    baseDmg: 26276,
    name: 'Claw of Qunard Rk. III'
  },
  CI: {
    baseDmg: 7237,
    castTime: 600,
    focusable: true,
    id: 'CI',
    level: 99,
    lockoutTime: 1500,
    manaCost: 714,
    name: 'Chaos Incandescence Rk. III',
    origCastTime: 750,
    recastTime: 4000,
    resist: 'FIRE',
    skill: 24,
    target: 'SINGLE',
    timer: 'chaosinc',
    type3DmgAug: 673
  },
  CO: {
    baseDmg: 23631,
    castTime: 1500,
    focusable: true,
    id: 'CO',
    level: 110,
    lockoutTime: 1500,
    manaCost: 1812,
    name: 'Claw of Travenro Rk. III',
    origCastTime: 3000,
    recastTime: 6000,
    resist: 'COLD',
    skill: 24,
    target: 'SINGLE',
    timer: '11',
    type3DmgAug: 1688
  },
  CORk1: {
    baseDmg: 21434,
    name: 'Claw of Travenro Rk. I'
  },
  CORk2: {
    baseDmg: 22506,
    name: 'Claw of Travenro Rk. II'
  },
  CORk3: {
    baseDmg: 23631,
    name: 'Claw of Travenro Rk. III'
  },
  CB: {
    baseDmg: 10577,
    canTwincast: false,
    castTime: 0,
    focusable: true,
    id: 'CB',
    level: 106,
    lockoutTime: 1500,
    manaCost: 100,
    name: 'Chaos Burn III',
    origCastTime: 0,
    recastTime: 4750,
    resist: 'FIRE',
    skill: 24,
    target: 'SINGLE',
    timer: 'chaosburn',
    type3DmgAug: 1005
  },
  CBRk1: {
    baseDmg: 9594,
    name: 'Chaos Burn I'
  },
  CBRk2: {
    baseDmg: 10073 ,
    name: 'Chaos Burn II'
  },
  CBRk3: {
    baseDmg: 10577,
    name: 'Chaos Burn III'
  },
  CT: {
    baseDmg: 21765,
    castTime: 0,
    focusable: true,
    id: 'CT',
    level: 107,
    lockoutTime: 1500,
    manaCost: 3699,
    name: 'Cloudburst Thunderbolt Rk. III',
    origCastTime: 0,
    recastTime: 3000,
    resist: 'MAGIC',
    skill: 24,
    target: 'SINGLE',
    timer: '2',
    type3DmgAug: 1555
  },
  CTRk1: {
    baseDmg: 19742,
    name: 'Cloudburst Thunderbolt Rk. I'
  },
  CTRk2: {
    baseDmg: 20729,
    name: 'Cloudburst Thunderbolt Rk. II'
  },
  CTRk3: {
    baseDmg: 21765,
    name: 'Cloudburst Thunderbolt Rk. III'
  },
  DF: {
    baseDmg: 140801,
    canTwincast: false,
    castTime: 1980,
    focusable: true,
    id: 'DF',
    level: 250,
    lockoutTime: 1500,
    manaCost: 100,
    name: 'Dissident Fire 6',
    origCastTime: 3000,
    recastTime: 60000,
    recastTime2: 6000,
    resist: 'FIRE',
    skill: 24,
    target: 'SINGLE',
    timer: 'dicho'
  },
  EI: {
    baseDmg: 36353,
    castTime: 1875,
    focusable: true,
    id: 'EI',
    level: 109,
    lockoutTime: 1500,
    manaCost: 5573,
    name: 'Ethereal Icefloe Rk. III',
    origCastTime: 3750,
    recastTime: 5250,
    resist: 'COLD',
    skill: 24,
    target: 'SINGLE',
    timer: 'eiceflow',
    type3DmgAug: 2887
  },
  EIRk1: {
    baseDmg: 32973,
    name: 'Ethereal Icefloe Rk. I'
  },
  EIRk2: {
    baseDmg: 34622,
    name: 'Ethereal Icefloe Rk. II'
  },
  EIRk3: {
    baseDmg: 36353,
    name: 'Ethereal Icefloe Rk. III'
  },
  ES: {
    baseDmg: 40421,
    castTime: 1875,
    focusable: true,
    id: 'ES',
    level: 110,
    lockoutTime: 1500,
    manaCost: 6196,
    name: 'Ethereal Skyfire Rk. III',
    origCastTime: 3750,
    recastTime: 5500,
    resist: 'FIRE',
    skill: 24,
    target: 'SINGLE',
    timer: 'skyfire',
    type3DmgAug: 2887
  },
  ESRk1: {
    baseDmg: 36663,
    name: 'Ethereal Skyfire Rk. I'
  },
  ESRk2: {
    baseDmg: 38496,
    name: 'Ethereal Skyfire Rk. II'
  },
  ESRk3: {
    baseDmg: 40421,
    name: 'Ethereal Skyfire Rk. III'
  },
  EV: {
    baseDmg: 34201,
    castTime: 1875,
    focusable: true,
    id: 'EV',
    level: 107,
    lockoutTime: 1500,
    manaCost: 5983,
    name: 'Ethereal Volley Rk. III',
    origCastTime: 3750,
    recastTime: 5500,
    resist: 'MAGIC',
    skill: 24,
    target: 'SINGLE',
    timer: 'evolley',
    type3DmgAug: 2887
  },
  EVRk1: {
    baseDmg: 31021,
    name: 'Ethereal Volley Rk. I'
  },
  EVRk2: {
    baseDmg: 32572,
    name: 'Ethereal Volley Rk. II'
  },
  EVRk3: {
    baseDmg: 34201,
    name: 'Ethereal Volley Rk. III'
  },
  ER: {
    baseDmg: 29975,
    castTime: 1875,
    focusable: true,
    id: 'ER',
    level: 104,
    lockoutTime: 1500,
    manaCost: 4639,
    name: 'Ethereal Rimeblast Rk. III',
    origCastTime: 3750,
    recastTime: 5250,
    resist: 'COLD',
    skill: 24,
    target: 'SINGLE',
    timer: 'rimeblast',
    type3DmgAug: 2381
  },
  EZ: {
    baseDmg: 33330,
    castTime: 1875,
    focusable: true,
    id: 'EZ',
    level: 105,
    lockoutTime: 1500,
    manaCost: 5158,
    name: 'Ethereal Skyblaze Rk. III',
    origCastTime: 3750,
    recastTime: 5500,
    resist: 'FIRE',
    skill: 24,
    target: 'SINGLE',
    timer: 'skyblaze',
    type3DmgAug: 2381
  },
  FBC: {
    castTime: 1980,
    focusable: true,
    id: 'FBC',
    level: 107,
    lockoutTime: 1500,
    manaCost: 13791,
    name: 'Frostbound Covenant Rk. III',
    origCastTime: 3000,
    recastTime: 60000,
    resist: 'COLD',
    skill: 5,
    target: 'SINGLE',
    timer: '14'
  },
  FAR: {
    baseDmg: 3121559,
    castTime: 1980,
    focusable: false,
    id: 'FAR',
    level: 255,
    lockoutTime: 0,
    manaCost: 0,
    max: 3121559,
    maxCritRate: 0,
    name: 'Frostbound Resolution III',
    origCastTime: 3000,
    recastTime: 0,
    resist: 'COLD',
    skill: 5,
    spellDmgCap: 0,
    target: 'SINGLE',
    timer: 'ff'
  },
  FB: {
    baseDmg: 18547,
    castTime: 0,
    focusable: true,
    id: 'FB',
    level: 104,
    lockoutTime: 1500,
    manaCost: 2964,
    name: 'Flashburn Rk. III',
    origCastTime: 0,
    recastTime: 8250,
    resist: 'FIRE',
    skill: 24,
    target: 'SINGLE',
    timer: '2',
    type3DmgAug: 1262
  },
  FBRk1: {
    baseDmg: 16823,
    name: 'Flashburn Rk. I'
  },
  FBRk2: {
    baseDmg: 17664,
    name: 'Flashburn Rk. II'
  },
  FBRk3: {
    baseDmg: 18547,
    name: 'Flashburn Rk. III'
  },
  FF4: {
    aa: true,
    baseDmg: 14010,
    castTime: 500,
    focusable: false,
    id: 'FF4',
    level: 254,
    lockoutTime: 0,
    manaCost: 1750,
    name: 'Force of Flame IV',
    origCastTime: 500,
    recastTime: 0,
    resist: 'FIRE',
    skill: 24,
    target: 'SINGLE',
    timer: '36'
  },
  FF5: {
    aa: true,
    baseDmg: 15000,
    castTime: 500,
    focusable: false,
    id: 'FF5',
    level: 254,
    lockoutTime: 0,
    manaCost: 1750,
    name: 'Force of Flame V',
    origCastTime: 500,
    recastTime: 0,
    resist: 'FIRE',
    skill: 24,
    target: 'SINGLE',
    timer: '36'
  },
  FF6: {
    aa: true,
    baseDmg: 15985,
    castTime: 500,
    focusable: false,
    id: 'FF6',
    level: 254,
    lockoutTime: 0,
    manaCost: 1750,
    name: 'Force of Flame VI',
    origCastTime: 500,
    recastTime: 0,
    resist: 'FIRE',
    skill: 24,
    target: 'SINGLE',
    timer: '36'
  },
  FF7: {
    aa: true,
    baseDmg: 17150,
    castTime: 500,
    focusable: false,
    id: 'FF7',
    level: 254,
    lockoutTime: 0,
    manaCost: 1750,
    name: 'Force of Flame VII',
    origCastTime: 500,
    recastTime: 0,
    resist: 'FIRE',
    skill: 24,
    target: 'SINGLE',
    timer: '36'
  },
  FF8: {
    aa: true,
    baseDmg: 18400,
    castTime: 500,
    focusable: false,
    id: 'FF8',
    level: 254,
    lockoutTime: 0,
    manaCost: 1750,
    name: 'Force of Flame VIII',
    origCastTime: 500,
    recastTime: 0,
    resist: 'FIRE',
    skill: 24,
    target: 'SINGLE',
    timer: '36'
  },
  FF9: {
    aa: true,
    baseDmg: 19500,
    castTime: 500,
    focusable: false,
    id: 'FF9',
    level: 254,
    lockoutTime: 0,
    manaCost: 1750,
    name: 'Force of Flame IX',
    origCastTime: 500,
    recastTime: 0,
    resist: 'FIRE',
    skill: 24,
    target: 'SINGLE',
    timer: '36'
  },
  FI4: {
    aa: true,
    baseDmg: 14010,
    castTime: 500,
    focusable: false,
    id: 'FI4',
    level: 254,
    lockoutTime: 0,
    manaCost: 1750,
    name: 'Force of Ice IV',
    origCastTime: 500,
    recastTime: 0,
    resist: 'COLD',
    skill: 24,
    target: 'SINGLE',
    timer: '44'
  },
  FI5: {
    aa: true,
    baseDmg: 15000,
    castTime: 500,
    focusable: false,
    id: 'FI5',
    level: 254,
    lockoutTime: 0,
    manaCost: 1750,
    name: 'Force of Ice V',
    origCastTime: 500,
    recastTime: 0,
    resist: 'COLD',
    skill: 24,
    target: 'SINGLE',
    timer: '44'
  },
  FI6: {
    aa: true,
    baseDmg: 15985,
    castTime: 500,
    focusable: false,
    id: 'FI6',
    level: 254,
    lockoutTime: 0,
    manaCost: 1750,
    name: 'Force of Ice VI',
    origCastTime: 500,
    recastTime: 0,
    resist: 'COLD',
    skill: 24,
    target: 'SINGLE',
    timer: '44'
  },
  FI7: {
    aa: true,
    baseDmg: 17150,
    castTime: 500,
    focusable: false,
    id: 'FI7',
    level: 254,
    lockoutTime: 0,
    manaCost: 1750,
    name: 'Force of Ice VII',
    origCastTime: 500,
    recastTime: 0,
    resist: 'COLD',
    skill: 24,
    target: 'SINGLE',
    timer: '44'
  },
  FI8: {
    aa: true,
    baseDmg: 18400,
    castTime: 500,
    focusable: false,
    id: 'FI8',
    level: 254,
    lockoutTime: 0,
    manaCost: 1750,
    name: 'Force of Ice VIII',
    origCastTime: 500,
    recastTime: 0,
    resist: 'COLD',
    skill: 24,
    target: 'SINGLE',
    timer: '44'
  },
  FI9: {
    aa: true,
    baseDmg: 19500,
    castTime: 500,
    focusable: false,
    id: 'FI9',
    level: 254,
    lockoutTime: 0,
    manaCost: 1750,
    name: 'Force of Ice IX',
    origCastTime: 500,
    recastTime: 0,
    resist: 'COLD',
    skill: 24,
    target: 'SINGLE',
    timer: '44'
  },
  EB: {
    castTime: 1500,
    focusable: true,
    id: 'EB',
    level: 110,
    lockoutTime: 1500,
    manaCost: 567,
    name: 'Ethereal Braid',
    origCastTime: 3000,
    recastTime: 36000,
    skill: 24,
    target: 'SINGLE',
    timer: '12'
  },
  FW24: {
    aa: true,
    baseDmg: 14010,
    castTime: 500,
    focusable: false,
    id: 'FW24',
    level: 254,
    lockoutTime: 0,
    manaCost: 1750,
    name: 'Force of Will XVI',
    origCastTime: 500,
    recastTime: 0,
    resist: 'MAGIC',
    skill: 24,
    target: 'SINGLE',
    timer: '37'
  },
  FW25: {
    aa: true,
    baseDmg: 15000,
    castTime: 500,
    focusable: false,
    id: 'FW25',
    level: 254,
    lockoutTime: 0,
    manaCost: 1750,
    name: 'Force of Will XVII',
    origCastTime: 500,
    recastTime: 0,
    resist: 'MAGIC',
    skill: 24,
    target: 'SINGLE',
    timer: '37'
  },
  FW26: {
    aa: true,
    baseDmg: 15985,
    castTime: 500,
    focusable: false,
    id: 'FW26',
    level: 254,
    lockoutTime: 0,
    manaCost: 1750,
    name: 'Force of Will XVIII',
    origCastTime: 500,
    recastTime: 0,
    resist: 'MAGIC',
    skill: 24,
    target: 'SINGLE',
    timer: '37'
  },
  FW27: {
    aa: true,
    baseDmg: 17150,
    castTime: 500,
    focusable: false,
    id: 'FW27',
    level: 254,
    lockoutTime: 0,
    manaCost: 1750,
    name: 'Force of Will XIX',
    origCastTime: 500,
    recastTime: 0,
    resist: 'MAGIC',
    skill: 24,
    target: 'SINGLE',
    timer: '37'
  },
  FW28: {
    aa: true,
    baseDmg: 18400,
    castTime: 500,
    focusable: false,
    id: 'FW28',
    level: 254,
    lockoutTime: 0,
    manaCost: 1750,
    name: 'Force of Will XX',
    origCastTime: 500,
    recastTime: 0,
    resist: 'MAGIC',
    skill: 24,
    target: 'SINGLE',
    timer: '37'
  },
  FW29: {
    aa: true,
    baseDmg: 19500,
    castTime: 500,
    focusable: false,
    id: 'FW29',
    level: 254,
    lockoutTime: 0,
    manaCost: 1750,
    name: 'Force of Will XXI',
    origCastTime: 500,
    recastTime: 0,
    resist: 'MAGIC',
    skill: 24,
    target: 'SINGLE',
    timer: '37'
  },
  HC: {
    baseDmg: 19104,
    castTime: 1500,
    focusable: true,
    id: 'HC',
    level: 99,
    lockoutTime: 1500,
    manaCost: 1964,
    name: 'Hoarfrost Cascade Rk. III',
    origCastTime: 3000,
    recastTime: 6000,
    resist: 'COLD',
    skill: 24,
    target: 'SINGLE',
    timer: 'hoarcascade',
    type3DmgAug: 1345
  },
  IC: {
    baseDmg: 25542,
    canTwincast: false,
    castTime: 0,
    focusable: true,
    id: 'IC',
    level: 106,
    lockoutTime: 1500,
    manaCost: 100,
    name: 'Icefloe Cascade III',
    origCastTime: 0,
    recastTime: 9000,
    resist: 'COLD',
    skill: 24,
    target: 'SINGLE',
    timer: 'iceflowcas',
    type3DmgAug: 1824
  },
  ICRk1: {
    baseDmg: 23168,
    name: 'Icefloe Cascade I'
  },
  ICRk2: {
    baseDmg: 24326,
    name: 'Icefloe Cascade II'
  },
  ICRk3: {
    baseDmg: 25542,
    name: 'Icefloe Cascade III'
  },
  ME: {
    baseDmg: 16294,
    castTime: 1500,
    focusable: true,
    id: 'ME',
    level: 109,
    lockoutTime: 1500,
    manaCost: 2019,
    maxCritRate: 0.40,
    maxHits: 4,
    name: 'Magmatic Explosion Rk. III',
    origCastTime: 3000,
    recastTime: 12000,
    resist: 'FIRE',
    skill: 24,
    target: 'TargetAE',
    timer: '6',
    type3DmgAug: 1095
  },
  MERk1: {
    baseDmg: 14779,
    name: 'Magmatic Explosion Rk. I'
  },
  MERk2: {
    baseDmg: 15518,
    name: 'Magmatic Explosion Rk. II'
  },
  MERk3: {
    baseDmg: 16294,
    name: 'Magmatic Explosion Rk. III'
  },
  MBRN: {
    baseDmg: 2800000,
    castTime: 3000,
    focusable: false,
    id: 'MBRN',
    level: 254,
    lockoutTime: 0,
    manaCost: 70000,
    maxCritRate: 0,
    name: 'Mana Burn XVI',
    origCastTime: 3000,
    recastTime: 1800,
    recastTime2: 0,
    resist: 'MAGIC',
    skill: 98,
    target: 'SINGLE',
    timer: 'MBRN'
  },
  PE: {
    baseDmg: 11272,
    castTime: 600,
    focusable: true,
    id: 'PE',
    level: 100,
    lockoutTime: 1500,
    manaCost: 50,
    name: 'Pure Wildether III',
    origCastTime: 750,
    recastTime: 4000,
    resist: 'MAGIC',
    skill: 24,
    target: 'SINGLE',
    timer: 'pwildether',
    type3DmgAug: 794
  },
  PF: {
    baseDmg: 15826,
    canTwincast: false,
    castTime: 600,
    focusable: true,
    id: 'PF',
    level: 105,
    lockoutTime: 1500,
    manaCost: 50,
    name: 'Pure Wildflash Caza',
    origCastTime: 750,
    recastTime: 4000,
    resist: 'MAGIC',
    skill: 24,
    target: 'SINGLE',
    timer: 'pwildflash',
    type3DmgAug: 1130
  },
  PFRk1: {
    baseDmg: 14345,
    name: 'Pure Wildflash Azia'
  },
  PFRk2: {
    baseDmg: 15072,
    name: 'Pure Wildflash Beza'
  },
  PFRk3: {
    baseDmg: 15826,
    name: 'Pure Wildflash Caza'
  },
  SC: {
    baseDmg: 20972,
    baseDmgUnMod: 20972,
    castTime: 1500,
    focusable: true,
    id: 'SC',
    level: 105,
    lockoutTime: 3000,
    manaCost: 2929,
    maxHits: 5,
    name: 'Self-Combustion Rk. III',
    origCastTime: 3000,
    recastTime: 15000,
    resist: 'FIRE',
    skill: 24,
    target: 'CasterPB',
    timer: '10'
  },
  SF: {
    baseDmg: 14400,
    castTime: 2000,
    focusable: true,
    id: 'SF',
    level: 109,
    lockoutTime: 1500,
    manaCost: 1866,
    maxHits: 4,
    name: 'Skyfire Pillar Rk. III',
    origCastTime: 2500,
    recastTime: 6000,
    resist: 'FIRE',
    skill: 24,
    target: 'TargetAE',
    timer: '8',
    type3DmgAug: 1003
  },
  SFRk1: {
    name: 'Skyfire Pillar Rk. I',
    baseDmg: 13601
  },
  SFRk2: {
    name: 'Skyfire Pillar Rk. II',
    baseDmg: 13714
  },
  SFRk3: {
    name: 'Skyfire Pillar Rk. III',
    baseDmg: 14400
  },
  SH: {
    baseDmg: 14184,
    baseDmgUnMod: 14184,
    castTime: 800,
    focusable: true,
    id: 'SH',
    level: 95,
    lockoutTime: 1500,
    manaCost: 2758,
    maxHits: 5,
    name: 'Splash of Phenocrysts Rk. III',
    origCastTime: 1000,
    recastTime: 35000,
    resist: 'FIRE',
    skill: 24,
    target: 'TargetRingAE',
    timer: 'splashphenoc'
  },
  SR: {
    baseDmg: 11696,
    baseDmgUnMod: 11696,
    castTime: 800,
    focusable: true,
    id: 'SR',
    level: 90,
    lockoutTime: 1500,
    manaCost: 2580,
    maxHits: 5,
    name: 'Splash of Rhyolite Rk. III',
    origCastTime: 1000,
    recastTime: 35000,
    resist: 'FIRE',
    skill: 24,
    target: 'TargetRingAE',
    timer: 'splashrhyolite'
  },
  SP: {
    baseDmg: 13991,
    baseDmgUnMod: 13991,
    castTime: 800,
    focusable: true,
    id: 'SP',
    level: 100,
    lockoutTime: 1500,
    manaCost: 2924,
    maxHits: 5,
    name: 'Splash of Pyroxene Rk. III',
    origCastTime: 1000,
    recastTime: 35000,
    resist: 'FIRE',
    skill: 24,
    target: 'TargetRingAE',
    timer: 'splashproxene'
  },
  SJ: {
    baseDmg: 19828,
    castTime: 800,
    focusable: true,
    id: 'SJ',
    level: 108,
    lockoutTime: 1500,
    manaCost: 1246,
    name: 'Stormjolt Vortex Rk. III',
    origCastTime: 1000,
    recastTime: 24000,
    resist: 'MAGIC',
    skill: 24,
    target: 'SINGLE',
    timer: 'vortex'
  },
  TW: {
    baseDmg: 24343,
    castTime: 1750,
    focusable: true,
    id: 'TW',
    level: 110,
    lockoutTime: 1500,
    manaCost: 2455,
    name: 'Thricewoven Capacity Rk. III',
    origCastTime: 3500,
    recastTime: 5000,
    resist: 'MAGIC',
    skill: 24,
    target: 'SINGLE',
    timer: 'thricecapacity',
    type3DmgAug: 1739
  },
  TWRk1: {
    baseDmg: 22080,
    name: 'Thricewoven Capacity Rk. I'
  },
  TWRk2: {
    baseDmg: 23184,
    name: 'Thricewoven Capacity Rk. II'
  },
  TWRk3: {
    baseDmg: 24343,
    name: 'Thricewoven Capacity Rk. III'
  },
  WE: {
    baseDmg: 0,
    castTime: 600,
    focusable: true,
    id: 'WE',
    level: 96,
    lockoutTime: 1500,
    manaCost: 583,
    name: 'Wildether Barrage Rk. III',
    origCastTime: 750,
    recastTime: 4000,
    resist: 'MAGIC',
    skill: 24,
    target: 'SINGLE',
    timer: 'wildether'
  },
  WF: {
    baseDmg: 0,
    castTime: 600,
    focusable: true,
    id: 'WF',
    level: 106,
    lockoutTime: 1500,
    manaCost: 669,
    name: 'Wildflash Strike Rk. III',
    origCastTime: 750,
    recastTime: 4000,
    resist: 'MAGIC',
    skill: 24,
    target: 'SINGLE',
    timer: 'wildflash'
  },
  WFRk1: {
    name: 'Wildflash Strike Rk. I'
  },
  WFRk2: {
    name: 'Wildflash Strike Rk. II'
  },
  WFRk3: {
    name: 'Wildflash Strike Rk. III'
  },
  WH: {
    baseDmg: 8763,
    castTime: 1600,
    focusable: true,
    id: 'WH',
    level: 106,
    lockoutTime: 1500,
    manaCost: 2044,
    maxHits: 20,
    name: 'Wheel of Flame Rk. III',
    origCastTime: 2000,
    recastTime: 6000,
    resist: 'FIRE',
    skill: 24,
    target: 'CasterPB',
    timer: '4'
  },
  WHRk1: {
    name: 'Wheel of Flame Rk. I',
    baseDmg: 7949
  },
  WHRk2: {
    name: 'Wheel of Flame Rk. II',
    baseDmg: 8346
  },
  WHRk3: {
    name: 'Wheel of Flame Rk. III',
    baseDmg: 8763
  }
};
